name: Precode Review
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v7
      # runner already has pre-installed NodeJS, this step just for test purposes
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 24
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test