name: Reusable
on:
  workflow_call:
    inputs:
      artifact-name:
        description: Name of the deployable artifact
        required: false
        default: dist
        type: string
    outputs:
      result:
        description: Deployment outcome
        value: ${{ jobs.deploy.outputs.outcome }}
    # secrets:
    #   some-secret:
    #     required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      outcome: ${{ steps.set-result-output.outputs.deploy-result }}
    steps:
      - name: Get built artifacts
        uses: actions/download-artifact@v8
        with:
          name: ${{ inputs.artifact-name }}
      - name: Output contents
        run: ls
      - name: Deploy
        run: echo "=== Deploying ==="
      - name: Set result output
        id: set-result-output
        run: echo 'deploy-result=success' >> $GITHUB_OUTPUT ';'



